--放置数据库对象及表数据的清理语句
/*SAAS模块*/
DROP TABLE IF EXISTS `TB_SERVICE_ORDER`;				--删除服务订单
DROP TABLE IF EXISTS `TB_SERVICE_VERSION`;			--删除服务版本
DROP TABLE IF EXISTS `TB_SERVICE_DEFINE`; 			--删除服务定义
DROP TABLE IF EXISTS `TB_SERVICE_CATEGORY`;		--删除服务目录


/* 系统基础模块 */
DROP TABLE IF EXISTS `TB_SYS_CONFIG` ;					--删除系统配置


/*产品模块*/
DROP TABLE IF EXISTS `TB_ACT_PRODUCTS` ;								--删除活动商品
DROP TABLE IF EXISTS `TB_PRD_PRTEXTATTR` ;							--删除产品属性
DROP TABLE IF EXISTS `TB_PRD_PRODUCT` ;								--删除产品
DROP TABLE IF EXISTS `TB_PRD_CATEGORYATTR` ;					--删除产品类目属性
DROP TABLE IF EXISTS `TB_PRD_CATEATTRGROUP` ;				--删除产品类目属性组
DROP TABLE IF EXISTS `TB_PRD_CATEGORY` ;								--删除产品类目


/*活动模块*/
DROP TABLE IF EXISTS `TB_ACT_TIMES` ;									--删除活动次数
DROP TABLE IF EXISTS `TB_ACT_ATTENDRD_FAILURE` ;		--删除发放失败记录表
DROP TABLE IF EXISTS `TB_ACT_ATTEND` ;								--删除活动参与记录
DROP TABLE IF EXISTS `TB_ACT_ACTIVITY` ;								--删除活动表
DROP TABLE IF EXISTS `TB_ACT_PRIZEITEM` ;							--删除奖项
DROP TABLE IF EXISTS `TB_ACT_PRIZEPOOL` ;						--删除奖池
DROP TABLE IF EXISTS `TB_ACT_PRIZETYPE` ;							--删除奖品类型

/*会员模块*/
DROP TABLE IF  EXISTS `TB_MEMBER_SHOP` ;						--删除卖家（商家） 三方平台的店铺信息
DROP TABLE IF  EXISTS `TB_MEMBER_SELLER_AUTH` ;			--删除第三方平台的卖家授权信息
DROP TABLE IF  EXISTS `TB_MEMBER_BUYER_MAPPING` ;	--删除第三方平台会员映射
DROP TABLE IF EXISTS `TB_MEMBER_BUYERINFO` ;				--删除会员信息
DROP TABLE IF EXISTS `TB_MEMBER_SELLER` ;						--删除卖家动态
DROP TABLE IF EXISTS `TB_MEMBER_DYNAMIC` ;					--删除买家动态
DROP TABLE IF EXISTS `TB_MEMBER_BUYER` ;						--删除买家信息


