--放置数据库对象及表数据的清理语句
/*产品管理模块*/
DROP TABLE IF EXISTS `TB_PQ_PRTEXTATTR`;				--产品扩展属性
DROP TABLE IF EXISTS `TB_PQ_PRODUCT`;					--删除产品
DROP TABLE IF EXISTS `TB_PQ_CATEGORYATTR`;				--产品类目属性
DROP TABLE IF EXISTS `TB_PQ_CATEGORYGROUP`;				--产品类目属性组
DROP TABLE IF EXISTS `TB_PQ_CATEGORY`;					--删除类目
