-------------------------------------------------产品管理模块------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `TB_PQ_CATEGORY` (
  `CATEGORY_ID` INT NOT NULL AUTO_INCREMENT COMMENT '类目标识',
  `CODE` VARCHAR(32) NOT NULL COMMENT '类目编码',
  `NAME` VARCHAR(64) NOT NULL COMMENT '类目名称',
  `PARENT_ID` INT NOT NULL DEFAULT -1 COMMENT '父类目，如果为顶级类目时为-1',
  `IS_LEAF` INT NOT NULL COMMENT '是否页子节点，页子节点才有属性信息。1为页子节点。',
  `STATUS` INT NOT NULL DEFAULT 1 COMMENT '状态：0为无效，1为有效，默认为1。',
  `HOLD1` VARCHAR(128) NULL,
  `METO` VARCHAR(128) NULL COMMENT '备注',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`CATEGORY_ID`))
ENGINE = InnoDB
COMMENT = '产品类目';


CREATE TABLE IF NOT EXISTS `TB_PQ_CATEGORYGROUP` (
  `GROUP_ID` INT NOT NULL AUTO_INCREMENT COMMENT '组ID',
  `CATEGORY_ID` INT NOT NULL COMMENT '类目标识',
  `NAME` VARCHAR(64) NULL,
  `STATUS` INT NULL DEFAULT 1,
  `METO` VARCHAR(128) NULL,
  PRIMARY KEY (`GROUP_ID`),
  INDEX `fk_TB_PQ_CATEGORYGROUP_TB_PQ_CATEGORY_idx` (`CATEGORY_ID` ASC),
  CONSTRAINT `fk_TB_PQ_CATEGORYGROUP_TB_PQ_CATEGORY`
    FOREIGN KEY (`CATEGORY_ID`)
    REFERENCES `QRCODE`.`TB_PQ_CATEGORY` (`CATEGORY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '产品类目属性组';


CREATE TABLE IF NOT EXISTS `TB_PQ_CATEGORYATTR` (
  `ATTR_ID` INT NOT NULL AUTO_INCREMENT COMMENT '类目属性ID',
  `GROUP_ID` INT NOT NULL COMMENT '属性组',
  `CNAME` VARCHAR(64) NOT NULL COMMENT '属性名称(中文)',
  `ENAME` VARCHAR(64) NULL COMMENT '属性名称（英文）',
  `DATA_TYPE` VARCHAR(8) NOT NULL DEFAULT '2' COMMENT '数据类型，1为NUMBER, 2为STRING，3为DATE,4为TIME\n5, REGION区域 6为COLOR,7维度值',
  `IS_MULT` INT NOT NULL DEFAULT 0 COMMENT '是否多值：0为单值，1为多值。默认为0',
  `SKU_FLG` INT NULL DEFAULT 0 COMMENT 'SKU属性，0为不是，1为是，默认为0',
  `MULT_VALUE` VARCHAR(256) NOT NULL COMMENT '当类型为维度值时，表示方法为{n1: v1, n2: v2, n3 : v3}',
  PRIMARY KEY (`ATTR_ID`),
  INDEX `fk_TB_PQ_CATEGORYATTR_TB_PQ_CATEGORYGROUP1_idx` (`GROUP_ID` ASC),
  CONSTRAINT `fk_TB_PQ_CATEGORYATTR_TB_PQ_CATEGORYGROUP1`
    FOREIGN KEY (`GROUP_ID`)
    REFERENCES `QRCODE`.`TB_PQ_CATEGORYGROUP` (`GROUP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '产品类目属性';


CREATE TABLE IF NOT EXISTS `TB_PQ_PRODUCT` (
  `PRODUCT_ID` INT NOT NULL AUTO_INCREMENT COMMENT '产品ID（主键）',
  `PRD_CODE` VARCHAR(64) NULL COMMENT '产品编码',
  `CATEGORY_ID` INT NOT NULL COMMENT '类目ID',
  `NAME` VARCHAR(128) NOT NULL COMMENT '名称',
  `BRAND` VARCHAR(128) NULL COMMENT '品牌',
  `TITLE` VARCHAR(64) NULL COMMENT '标题',
  `PRICE` INT NULL COMMENT '价格',
  `IMAGE1_URL` VARCHAR(128) NULL COMMENT '产品图像地址',
  `IMAGE2_URL` VARCHAR(128) NULL COMMENT '产品图像地址',
  `IMAGE3_URL` VARCHAR(128) NULL COMMENT '产品图像地址',
  `PRO_URL` VARCHAR(128) NULL COMMENT '产品链接 ',
  `METO` VARCHAR(128) NULL COMMENT '备注',
  `STATUS` INT NULL DEFAULT 1 COMMENT '状态，0为无效，1为有效。',
  `SELLER_NICK` VARCHAR(128) NULL COMMENT '产品所属买家',
  `CREATE_TIME` DATETIME NOT NULL,
  `UPDATE_TIME` DATETIME NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`),
  INDEX `fk_TB_PQ_PRODUCT_TB_PQ_CATEGORY1_idx` (`CATEGORY_ID` ASC),
  CONSTRAINT `fk_TB_PQ_PRODUCT_TB_PQ_CATEGORY1`
    FOREIGN KEY (`CATEGORY_ID`)
    REFERENCES `QRCODE`.`TB_PQ_CATEGORY` (`CATEGORY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '产品';


CREATE TABLE IF NOT EXISTS `TB_PQ_PRTEXTATTR` (
  `EXTATTR_ID` INT NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` INT NOT NULL,
  `ATTR_VALUES` VARCHAR(20000) NULL COMMENT '属性值，表达方式为属性ID:属性值,  {attr1: v1, attr2:[v2_1,v2_2]}',
  PRIMARY KEY (`EXTATTR_ID`),
  INDEX `fk_TB_PQ_PRTEXTATTR_TB_PQ_PRODUCT1_idx` (`PRODUCT_ID` ASC),
  CONSTRAINT `fk_TB_PQ_PRTEXTATTR_TB_PQ_PRODUCT1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `QRCODE`.`TB_PQ_PRODUCT` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '产品扩展属性';
